(function(){
'use strict';
const IRGUN_DIRECT_HOSTS=new Set(['test.irgunshiuraitorah.com','irgunshiuraitorah.com','www.irgunshiuraitorah.com','localhost']);
const IRGUN_DIRECT_PROTOCOL=String(location.protocol||'').toLowerCase();
if(!IRGUN_DIRECT_HOSTS.has(String(location.hostname||'').toLowerCase())&&!['capacitor:','ionic:'].includes(IRGUN_DIRECT_PROTOCOL)) return;
let hlsPromise=null;
const SPEEDS=[.75,1,1.25,1.5,1.75,2];
const fmt=s=>{s=Math.max(0,Math.floor(Number(s)||0));const h=Math.floor(s/3600),m=Math.floor(s%3600/60),x=s%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`:`${m}:${String(x).padStart(2,'0')}`};
function loadHls(api){if(window.Hls)return Promise.resolve(window.Hls);if(hlsPromise)return hlsPromise;hlsPromise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=`${api}/media-player/hls.js`;s.async=true;const t=setTimeout(()=>{s.remove();hlsPromise=null;reject(new Error('HLS library timed out'))},12000);s.onload=()=>{clearTimeout(t);window.Hls?resolve(window.Hls):reject(new Error('HLS library unavailable'))};s.onerror=()=>{clearTimeout(t);hlsPromise=null;reject(new Error('HLS library failed to load'))};document.head.appendChild(s)});return hlsPromise}
class Player{
 constructor(o={}){this.c=o.container;this.iframe=o.iframe;this.api=String(o.apiBase||'').replace(/\/$/,'');this.cb=o;this.hls=null;this.backend='none';this.url='';this.sources={};this.loading=false;this.token=0;this.build()}
 build(){const r=document.createElement('div');r.id='directMediaPlayer';r.className='direct-media-player';r.hidden=true;r.innerHTML=`<video id="directVideoElement" class="direct-media-video" playsinline webkit-playsinline="true" preload="metadata"></video><div id="dmLoading" class="direct-media-loading" hidden><span class="direct-media-spinner"></span><span>Loading video...</span></div><div id="dmError" class="direct-media-error" hidden><span id="dmErrorText"></span><button id="dmRetry" type="button">Try Again</button></div><div class="direct-media-controls"><button id="dmPlay" class="direct-media-icon-button" type="button"><i class="fa-solid fa-play"></i></button><span id="dmNow" class="direct-media-time">0:00</span><input id="dmSeek" class="direct-media-seek" type="range" min="0" max="1000" value="0"><span id="dmDur" class="direct-media-time">0:00</span><button id="dmMute" class="direct-media-icon-button" type="button"><i class="fa-solid fa-volume-high"></i></button><input id="dmVol" class="direct-media-volume" type="range" min="0" max="1" step=".05" value="1"><select id="dmSpeed" class="direct-media-select">${SPEEDS.map(x=>`<option value="${x}"${x===1?' selected':''}>${x}x</option>`).join('')}</select><select id="dmQuality" class="direct-media-select" hidden><option value="-1">Auto</option></select><button id="dmPip" class="direct-media-icon-button" type="button" aria-label="Picture in Picture" title="Picture in Picture"><i class="fa-solid fa-window-restore"></i></button><button id="dmFull" class="direct-media-icon-button" type="button" aria-label="Fullscreen" title="Fullscreen"><i class="fa-solid fa-expand"></i></button></div>`;this.c.appendChild(r);this.r=r;this.v=r.querySelector('video');this.load=r.querySelector('#dmLoading');this.err=r.querySelector('#dmError');this.errText=r.querySelector('#dmErrorText');this.playBtn=r.querySelector('#dmPlay');this.seek=r.querySelector('#dmSeek');this.now=r.querySelector('#dmNow');this.dur=r.querySelector('#dmDur');this.vol=r.querySelector('#dmVol');this.mute=r.querySelector('#dmMute');this.speed=r.querySelector('#dmSpeed');this.v.defaultPlaybackRate=1;this.v.playbackRate=1;this.speed.value='1';this.quality=r.querySelector('#dmQuality');this.pipBtn=r.querySelector('#dmPip');this.bind()}
 bind(){const v=this.v;this.playBtn.onclick=()=>v.paused?this.play().catch(()=>{}):v.pause();v.onclick=this.playBtn.onclick;v.onplay=()=>{this.loading=false;this.load.hidden=true;this.err.hidden=true;this.icons();this.cb.onPlay?.(this.state())};v.onpause=()=>{this.icons();if(!this.loading&&!v.ended)this.cb.onPause?.(this.state())};v.ontimeupdate=()=>{this.timeline();this.cb.onTimeUpdate?.(this.state())};v.ondurationchange=()=>this.timeline();v.onended=()=>this.cb.onEnded?.(this.state());v.onwaiting=v.onstalled=()=>{if(!v.paused){this.load.hidden=false}};v.onplaying=v.oncanplay=()=>{this.load.hidden=true};v.onerror=()=>{if(!this.loading&&v.error)setTimeout(()=>this.fatal(new Error('Direct video playback failed')),0)};const seekFromPointer=e=>{const d=this.duration();if(!d)return;const rect=this.seek.getBoundingClientRect();if(!rect.width)return;const clientX=Number(e.clientX);if(!Number.isFinite(clientX))return;const x=Math.max(0,Math.min(rect.width,clientX-rect.left));const ratio=x/rect.width;this.seek.value=String(Math.round(ratio*1000));this.now.textContent=fmt(d*ratio);void this.seekTo(d*ratio)};this.seek.onpointerdown=e=>{if(e.pointerType!=="touch"&&typeof e.button==="number"&&e.button!==0)return;seekFromPointer(e)};this.seek.onclick=seekFromPointer;this.seek.oninput=()=>{const d=this.duration();this.now.textContent=fmt(d*Number(this.seek.value)/1000)};this.seek.onchange=()=>this.seekTo(this.duration()*Number(this.seek.value)/1000);this.mute.onclick=()=>v.muted=!v.muted;this.vol.oninput=()=>{v.volume=Number(this.vol.value);if(v.volume)v.muted=false};v.onvolumechange=()=>this.volumeUI();this.speed.onchange=()=>this.setPlaybackRate(Number(this.speed.value));this.quality.onchange=()=>{if(this.hls)this.hls.currentLevel=Number(this.quality.value)};rpip(this.pipBtn,v);rfull(this.r.querySelector('#dmFull'),this.r,v);this.r.querySelector('#dmRetry').onclick=()=>this.activate(this.sources,this.current(),!v.paused,true).catch(e=>this.notify(e));this.icons();this.volumeUI()}
 icons(){this.playBtn.innerHTML=`<i class="fa-solid fa-${!this.v.paused&&!this.v.ended?'pause':'play'}"></i>`}
 volumeUI(){const m=this.v.muted||this.v.volume===0;this.vol.value=String(this.v.volume);this.mute.innerHTML=`<i class="fa-solid fa-${m?'volume-xmark':this.v.volume<.5?'volume-low':'volume-high'}"></i>`}
 timeline(){const d=this.duration(),c=this.current();this.now.textContent=fmt(c);this.dur.textContent=fmt(d);this.seek.value=d?String(Math.round(c/d*1000)):'0'}
 clear(){if(this.hls){try{this.hls.destroy()}catch(_){}this.hls=null}try{this.v.pause()}catch(_){}this.v.removeAttribute('src');try{this.v.load()}catch(_){}this.backend='none';this.url='';this.quality.hidden=true;this.quality.innerHTML='<option value="-1">Auto</option>'}
 meta(token,ms=12000){if(this.v.readyState>=1)return Promise.resolve();return new Promise((res,rej)=>{const done=()=>{cl();token===this.token?res():rej(new Error('source replaced'))},bad=()=>{cl();rej(new Error('video metadata failed'))},cl=()=>{clearTimeout(t);this.v.removeEventListener('loadedmetadata',done);this.v.removeEventListener('error',bad)},t=setTimeout(()=>{cl();rej(new Error('video metadata timed out'))},ms);this.v.addEventListener('loadedmetadata',done,{once:true});this.v.addEventListener('error',bad,{once:true})})}
 async mp4(url,pos,auto){const token=++this.token;this.loading=true;this.load.hidden=false;this.err.hidden=true;this.clear();this.backend='mp4';this.url=url;this.v.src=url;this.v.load();await this.meta(token);await this.seekTo(pos);this.loading=false;this.load.hidden=true;if(auto)await this.play().catch(()=>{});return this.backend}
 async hlsLoad(url,pos,auto){const token=++this.token;this.loading=true;this.load.hidden=false;this.err.hidden=true;this.clear();let H=null;try{H=await loadHls(this.api)}catch(_){}if(H?.isSupported?.()){const h=new H({enableWorker:true,lowLatencyMode:false,backBufferLength:60,maxBufferLength:30,maxMaxBufferLength:60,startPosition:Math.max(0,Number(pos)||0),capLevelToPlayerSize:true});this.hls=h;this.backend='hls-js';this.url=url;await new Promise((res,rej)=>{let done=false;const t=setTimeout(()=>finish(new Error('HLS manifest timeout')),12000),finish=e=>{if(done)return;done=true;clearTimeout(t);e?rej(e):res()};h.on(H.Events.MANIFEST_PARSED,()=>finish());h.on(H.Events.ERROR,(_e,d)=>{if(d?.fatal){if(!done)finish(new Error(`HLS failed: ${d.details||'fatal error'}`));else if(token===this.token)this.fatal(new Error(`HLS playback failed: ${d.details||'fatal error'}`))}});h.attachMedia(this.v);h.loadSource(url)});if(token!==this.token)throw new Error('source replaced');this.quality.innerHTML='<option value="-1">Auto</option>';for(const [i,l] of (h.levels||[]).entries()){const o=document.createElement('option');o.value=String(i);o.textContent=l.height?`${l.height}p`:`Quality ${i+1}`;this.quality.appendChild(o)}this.quality.hidden=(h.levels||[]).length<=1;await this.meta(token).catch(()=>{});await this.seekTo(pos);this.loading=false;this.load.hidden=true;if(auto)await this.play().catch(()=>{});return this.backend}if(this.v.canPlayType('application/vnd.apple.mpegurl')){this.backend='hls-native';this.url=url;this.v.src=url;this.v.load();await this.meta(token);await this.seekTo(pos);this.loading=false;this.load.hidden=true;if(auto)await this.play().catch(()=>{});return this.backend}throw new Error('HLS unsupported')}
 async activate(src={},pos=0,auto=false,force=false){this.sources={hls:String(src.hls||''),mp4:String(src.mp4||'')};this.show();const same=!force&&((this.sources.hls&&this.url===this.sources.hls&&this.backend.startsWith('hls'))||(this.sources.mp4&&this.url===this.sources.mp4&&this.backend==='mp4'));if(same){await this.seekTo(pos);if(auto)await this.play().catch(()=>{});return{backend:this.backend}}let he;if(this.sources.hls){try{return{backend:await this.hlsLoad(this.sources.hls,pos,auto)}}catch(e){he=e}}if(this.sources.mp4){try{return{backend:await this.mp4(this.sources.mp4,pos,auto)}}catch(e){throw new Error(`Direct video failed${he?`; HLS: ${he.message}`:''}; MP4: ${e.message}`)}}throw he||new Error('No direct video source')}
 fatal(e){if(this.backend.startsWith('hls')&&this.sources.mp4){const p=this.current(),a=!this.v.paused;this.mp4(this.sources.mp4,p,a).catch(x=>this.notify(x));return}this.notify(e)}
 notify(e){this.load.hidden=true;this.err.hidden=false;this.errText.textContent=String(e?.message||e||'Video failed');this.cb.onFatal?.({error:e,position:this.current(),autoplay:!this.v.paused,backend:this.backend})}
 current(){return Math.max(0,Number(this.v?.currentTime)||0)} duration(){const d=Number(this.v?.duration);return Number.isFinite(d)&&d>0?d:0} state(){return{position:this.current(),duration:this.duration(),paused:this.v.paused,ended:this.v.ended,playbackRate:this.v.playbackRate,backend:this.backend}}
 async seekTo(x){let n=Math.max(0,Number(x)||0),d=this.duration();if(d)n=Math.min(n,Math.max(0,d-.25));try{this.v.currentTime=n}catch(_){}this.timeline();return n}
 wakeVideoLayer(){const v=this.v;if(!v)return;try{v.playsInline=true;v.setAttribute('playsinline','');v.setAttribute('webkit-playsinline','true');v.style.display='block';v.style.visibility='visible';v.style.opacity='1';v.style.willChange='transform,opacity';v.style.webkitBackfaceVisibility='hidden';v.style.backfaceVisibility='hidden';if(typeof v.webkitSetPresentationMode==='function'&&v.webkitPresentationMode!=='picture-in-picture')try{v.webkitSetPresentationMode('inline')}catch(_){}v.style.webkitTransform='translate3d(0,0,0)';v.style.transform='translate3d(0,0,0)';void v.offsetWidth;try{v.getBoundingClientRect()}catch(_){}requestAnimationFrame(()=>{try{v.style.webkitTransform='translate3d(0,0,.001px)';v.style.transform='translate3d(0,0,.001px)';requestAnimationFrame(()=>{v.style.webkitTransform='translate3d(0,0,0)';v.style.transform='translate3d(0,0,0)'})}catch(_){}})}catch(_){}}
 async waitForVisualFrame(timeout=700){const v=this.v;if(!v||v.paused)return false;if(typeof v.requestVideoFrameCallback==='function')return await new Promise(resolve=>{let done=false;const finish=x=>{if(done)return;done=true;clearTimeout(timer);resolve(Boolean(x))};const timer=setTimeout(()=>finish(false),timeout);try{v.requestVideoFrameCallback(()=>finish(true))}catch(_){finish(false)}});const beforeFrames=Number(v.webkitDecodedFrameCount);const beforeTime=this.current();await new Promise(resolve=>setTimeout(resolve,Math.min(timeout,320)));const afterFrames=Number(v.webkitDecodedFrameCount);const advanced=this.current()>beforeTime+.04;const decoded=Number.isFinite(beforeFrames)&&Number.isFinite(afterFrames)?afterFrames>beforeFrames:false;return Boolean(!v.paused&&v.readyState>=2&&(decoded||advanced))}
 async relatchInlineVideoLayer(){const v=this.v;if(!v)return false;const at=this.current(),d=this.duration();try{v.playsInline=true;v.setAttribute('playsinline','');v.setAttribute('webkit-playsinline','true');if(typeof v.webkitSetPresentationMode==='function'&&v.webkitPresentationMode!=='picture-in-picture')v.webkitSetPresentationMode('inline')}catch(_){}try{v.style.display='block';v.style.visibility='visible';v.style.opacity='1';v.style.willChange='transform,opacity';v.style.webkitBackfaceVisibility='hidden';v.style.backfaceVisibility='hidden';v.style.webkitTransform='translate3d(0,0,.001px)';v.style.transform='translate3d(0,0,.001px)';void v.offsetWidth;try{v.getBoundingClientRect()}catch(_){}}catch(_){}const target=d>0?Math.min(Math.max(0,at+.02),Math.max(0,d-.15)):Math.max(0,at+.02);try{if(v.readyState>=1)v.currentTime=target}catch(_){}if(this.hls?.startLoad)try{this.hls.startLoad(target)}catch(_){}if(v.paused)try{await v.play()}catch(_){}await new Promise(resolve=>requestAnimationFrame(resolve));try{v.style.webkitTransform='translate3d(0,0,0)';v.style.transform='translate3d(0,0,0)'}catch(_){}if(v.paused){await new Promise(resolve=>setTimeout(resolve,80));try{await v.play()}catch(_){}}this.wakeVideoLayer();return !v.paused}
 async play(){this.show();this.wakeVideoLayer();if(this.hls?.startLoad)try{this.hls.startLoad(this.current())}catch(_){}await this.v.play();this.wakeVideoLayer();return true}
 async ensureVisualPlayback(forceRelatch=false){this.show();this.wakeVideoLayer();try{this.v.autoplay=true;this.v.setAttribute('autoplay','')}catch(_){}if(this.v.paused)try{await this.play()}catch(_){}let frameSeen=await this.waitForVisualFrame(700);const nativeShell=['capacitor:','ionic:'].includes(String(location.protocol||'').toLowerCase());if(forceRelatch||(!frameSeen&&nativeShell)){const relatched=await this.relatchInlineVideoLayer();if(relatched)frameSeen=await this.waitForVisualFrame(700)}if(this.v.paused){if(this.hls?.startLoad)try{this.hls.startLoad(this.current())}catch(_){}try{await this.v.play()}catch(_){}}if(this.v.paused){await new Promise(resolve=>setTimeout(resolve,120));try{await this.v.play()}catch(_){}}this.wakeVideoLayer();return !this.v.paused}
 pause(stop=true){this.v.pause();if(stop&&this.hls?.stopLoad)try{this.hls.stopLoad()}catch(_){}} setPlaybackRate(x){x=SPEEDS.includes(Number(x))?Number(x):1;this.v.playbackRate=x;this.speed.value=String(x)} show(){this.r.hidden=false;if(this.iframe)this.iframe.style.display='none'} showVimeo(){this.pause(true);this.r.hidden=true;if(this.iframe)this.iframe.style.display='block'}
}
function rpip(btn,v){if(!btn)return;const standard=()=>Boolean(document.pictureInPictureEnabled&&typeof v.requestPictureInPicture==='function');const webkit=()=>{try{return typeof v.webkitSetPresentationMode==='function'&&typeof v.webkitSupportsPresentationMode==='function'&&v.webkitSupportsPresentationMode('picture-in-picture')}catch(_){return false}};const supported=standard()||webkit();btn.hidden=!supported;if(!supported)return;const active=()=>document.pictureInPictureElement===v||v.webkitPresentationMode==='picture-in-picture';const update=()=>{const on=active();btn.classList.toggle('active',on);btn.setAttribute('aria-label',on?'Exit Picture in Picture':'Picture in Picture');btn.title=on?'Exit Picture in Picture':'Picture in Picture';btn.innerHTML=`<i class="fa-solid fa-${on?'arrow-right-from-bracket':'window-restore'}"></i>`};btn.onclick=async()=>{try{if(document.pictureInPictureElement===v&&document.exitPictureInPicture){await document.exitPictureInPicture()}else if(standard()){await v.requestPictureInPicture()}else if(webkit()){v.webkitSetPresentationMode(active()?'inline':'picture-in-picture')}}catch(e){console.warn('Picture-in-Picture failed',e)}update()};v.addEventListener('enterpictureinpicture',update);v.addEventListener('leavepictureinpicture',update);v.addEventListener('webkitpresentationmodechanged',update);update()}
function rfull(btn,root,v){btn.onclick=()=>{if(document.fullscreenElement){document.exitFullscreen?.();return}if(root.requestFullscreen)root.requestFullscreen().catch(()=>{});else try{v.webkitEnterFullscreen?.()}catch(_){}}}
window.ISTDirectMediaPlayer=Player;
})();
